-- Add sell rate (per 8g) and computed sell totals.

ALTER TABLE "salesNTX"
ADD COLUMN IF NOT EXISTS "sellRatePer8g" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "sellSubTotal" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "sales"
ADD COLUMN IF NOT EXISTS "sellCost" DECIMAL(65,30) NOT NULL DEFAULT 0;

