DELETE FROM "general_ledger_accounts"
WHERE "account_number" IN ('GL-000001', 'GL-000002', 'GL-000003', 'GL-000004');

INSERT INTO "general_ledger_accounts" ("account_number", "name", "updated_at")
VALUES
  ('1000', 'Sales', CURRENT_TIMESTAMP),
  ('1011', 'SundrySales', CURRENT_TIMESTAMP),
  ('1012', 'Sale Of Gold', CURRENT_TIMESTAMP),
  ('1031', 'Sales Return', CURRENT_TIMESTAMP),
  ('2001', 'Opening Stock', CURRENT_TIMESTAMP),
  ('2011', 'Purchases', CURRENT_TIMESTAMP),
  ('2012', 'Sundry Purchases', CURRENT_TIMESTAMP),
  ('2021', 'B/Purchases', CURRENT_TIMESTAMP),
  ('2041', 'Labour Charges', CURRENT_TIMESTAMP),
  ('2051', 'Other Expenses', CURRENT_TIMESTAMP),
  ('2052', 'Repair Charges', CURRENT_TIMESTAMP),
  ('2070', 'Purchases Return', CURRENT_TIMESTAMP),
  ('3011', 'Discount Received', CURRENT_TIMESTAMP),
  ('3016', 'Sundry Income', CURRENT_TIMESTAMP),
  ('3017', 'Repair Income', CURRENT_TIMESTAMP),
  ('3018', 'Commission Income', CURRENT_TIMESTAMP),
  ('4001', 'Salaries', CURRENT_TIMESTAMP),
  ('4002', 'Printing & Stationery', CURRENT_TIMESTAMP),
  ('4003', 'Staf Mess Expenses', CURRENT_TIMESTAMP),
  ('4004', 'Accounting Fee', CURRENT_TIMESTAMP),
  ('4005', 'Rent', CURRENT_TIMESTAMP),
  ('4006', 'Electrical Appliances', CURRENT_TIMESTAMP),
  ('4007', 'Electricity', CURRENT_TIMESTAMP),
  ('4008', 'Postage', CURRENT_TIMESTAMP),
  ('4009', 'Water', CURRENT_TIMESTAMP),
  ('4010', 'Travelling', CURRENT_TIMESTAMP),
  ('4011', 'Fax', CURRENT_TIMESTAMP),
  ('4012', 'Suntel Telephone', CURRENT_TIMESTAMP),
  ('4013', 'Petrol For Generator', CURRENT_TIMESTAMP),
  ('4014', 'Scale License', CURRENT_TIMESTAMP),
  ('4015', 'Accountancy Fee - Ananda', CURRENT_TIMESTAMP),
  ('4016', 'Telephone', CURRENT_TIMESTAMP),
  ('4017', 'Municiple License', CURRENT_TIMESTAMP),
  ('4018', 'Clarical Chgs - Somasena', CURRENT_TIMESTAMP),
  ('4019', 'EPF / ETF', CURRENT_TIMESTAMP),
  ('4020', 'ETF', CURRENT_TIMESTAMP),
  ('4021', 'Staff Bonus', CURRENT_TIMESTAMP),
  ('4022', 'Shop Maintenance', CURRENT_TIMESTAMP),
  ('4023', 'CCTV', CURRENT_TIMESTAMP),
  ('4024', 'Pads', CURRENT_TIMESTAMP),
  ('4101', 'Packing Material', CURRENT_TIMESTAMP),
  ('4102', 'Sales Commission', CURRENT_TIMESTAMP),
  ('4103', 'Discount Allowed', CURRENT_TIMESTAMP),
  ('4104', 'Coloring Charges', CURRENT_TIMESTAMP),
  ('4105', 'Advertisement', CURRENT_TIMESTAMP),
  ('4106', 'Customer Entertainment', CURRENT_TIMESTAMP),
  ('4107', 'BTT 10%', CURRENT_TIMESTAMP),
  ('4108', 'NBT', CURRENT_TIMESTAMP),
  ('4109', 'VAT', CURRENT_TIMESTAMP),
  ('4110', 'Bad Debts', CURRENT_TIMESTAMP),
  ('4111', 'Discount On Credit Card', CURRENT_TIMESTAMP),
  ('4112', 'No Order Advance', CURRENT_TIMESTAMP),
  ('4201', 'Bank Charges', CURRENT_TIMESTAMP),
  ('4202', 'OD Interest', CURRENT_TIMESTAMP),
  ('4204', 'Commission', CURRENT_TIMESTAMP),
  ('4205', 'Donation', CURRENT_TIMESTAMP),
  ('4206', 'Charity', CURRENT_TIMESTAMP),
  ('4207', 'General Expenses', CURRENT_TIMESTAMP),
  ('4208', 'News Paper', CURRENT_TIMESTAMP),
  ('4209', 'Security Fee', CURRENT_TIMESTAMP),
  ('4210', 'Shop Repair Expenses', CURRENT_TIMESTAMP),
  ('5001', 'Building', CURRENT_TIMESTAMP),
  ('5006', 'House', CURRENT_TIMESTAMP),
  ('5016', 'Furniture & Fittings', CURRENT_TIMESTAMP),
  ('5021', 'Scale', CURRENT_TIMESTAMP),
  ('5026', 'Air Conditioner', CURRENT_TIMESTAMP),
  ('5031', 'Generator', CURRENT_TIMESTAMP),
  ('5036', 'Vehicle', CURRENT_TIMESTAMP),
  ('5041', 'Camera System', CURRENT_TIMESTAMP),
  ('5045', 'Computer System', CURRENT_TIMESTAMP),
  ('6001', 'Cash', CURRENT_TIMESTAMP),
  ('6006', 'Peoples Bank', CURRENT_TIMESTAMP),
  ('6008', 'UB', CURRENT_TIMESTAMP),
  ('6010', 'BOC', CURRENT_TIMESTAMP),
  ('6018', 'Amana Bank', CURRENT_TIMESTAMP),
  ('6021', 'Debtors', CURRENT_TIMESTAMP),
  ('6061', 'Trade Debtors', CURRENT_TIMESTAMP),
  ('6301', 'Suspense A/C', CURRENT_TIMESTAMP),
  ('6303', 'Saving A/C', CURRENT_TIMESTAMP),
  ('7001', 'Creditors', CURRENT_TIMESTAMP),
  ('7006', 'Orders', CURRENT_TIMESTAMP),
  ('7201', 'Payable - Rent', CURRENT_TIMESTAMP),
  ('7202', 'Payable - Accounting Fee', CURRENT_TIMESTAMP),
  ('7203', 'Payable - Donation', CURRENT_TIMESTAMP),
  ('7204', 'Payable - Commission', CURRENT_TIMESTAMP),
  ('7205', 'Payable - Electricity', CURRENT_TIMESTAMP),
  ('7207', 'Payable - EPF/ETF', CURRENT_TIMESTAMP),
  ('7208', 'Payable - Salary', CURRENT_TIMESTAMP),
  ('7209', 'Payable - Telephone', CURRENT_TIMESTAMP),
  ('7210', 'Payable - General', CURRENT_TIMESTAMP),
  ('8001', 'Bank Loan', CURRENT_TIMESTAMP),
  ('9001', 'Capital', CURRENT_TIMESTAMP),
  ('9021', 'Income Tax', CURRENT_TIMESTAMP)
ON CONFLICT ("account_number") DO UPDATE
SET "name" = EXCLUDED."name",
    "updated_at" = CURRENT_TIMESTAMP;
