ALTER TABLE "transactions"
ADD COLUMN IF NOT EXISTS "gold_issued" DECIMAL(12,3) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "gold_received" DECIMAL(12,3) NOT NULL DEFAULT 0;

ALTER TABLE "salesNTX"
ADD COLUMN IF NOT EXISTS "totalStoneWeight" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "totalNetWeight" DECIMAL(65,30) NOT NULL DEFAULT 0;

UPDATE "salesNTX"
SET "totalNetWeight" = "totalGoldWeight"
WHERE "totalNetWeight" = 0;

ALTER TABLE "sales"
ADD COLUMN IF NOT EXISTS "stoneWeight" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "netWeight" DECIMAL(65,30) NOT NULL DEFAULT 0;

UPDATE "sales"
SET "netWeight" = "goldWeight"
WHERE "netWeight" = 0;
